/* === SiMSET Showroom — App Logic === */

/* -------- Data source -------- */
// Static JSON files generated by GitHub Actions every 15 minutes.
// No API key or external calls needed at runtime.
const DATA_BASE = './data';

const STATUS_LABEL = {
    ready: 'พร้อมใช้งาน',
    in_use: 'ถูกยืม',
    maintenance: 'รอซ่อม ใช้งานได้',
    broken: 'รอซ่อม ใช้งานไม่ได้',
    pending_disposal: 'รอจำหน่าย',
    disposed: 'จำหน่ายแล้ว/ส่งคืน',
    dept_purchase: 'จัดซื้อให้หน่วยงาน',
    pending_transfer: 'รอโอนย้าย',
    transferred: 'โอนย้ายแล้ว'
};

const STATUS_CLASS = {
    ready: 'ready',
    in_use: 'in-use',
    maintenance: 'warn',
    broken: 'bad',
    pending_disposal: 'warn-red',
    disposed: 'grey',
    dept_purchase: 'info',
    pending_transfer: 'warn',
    transferred: 'grey'
};

const TYPE_EMOJI = { ADULT: '🟠', CHILD: '🟡', INFANT: '🔵' };
const TYPE_LABEL = { ADULT: 'ผู้ใหญ่', CHILD: 'เด็ก', INFANT: 'ทารก' };
const TYPE_CSS = { ADULT: 'adult', CHILD: 'child', INFANT: 'infant', null: 'other' };

let allManikins = [];
let locationMap = {};
let capMap = {};
let manikinCaps = {};   // sapId → [capLabel, ...]
let viewMode = 'grouped';
let filterAge = 'all';
let filterStatus = 'all';
let searchQuery = '';

/* -------- Helpers -------- */

const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

// Mask SAP ID — show only last 4 characters to reduce internal identifier leakage
const maskSap = s => { const str = String(s ?? ''); return str.length > 4 ? '···' + str.slice(-4) : str; };

// Debounced render — batches burst Realtime events (max wait 1s to prevent starvation)
let _renderTimer = null;
let _renderMaxTimer = null;
function scheduleRender() {
    if (!_renderMaxTimer) {
        _renderMaxTimer = setTimeout(() => {
            clearTimeout(_renderTimer);
            _renderTimer = null;
            _renderMaxTimer = null;
            updateStats(allManikins);
            render();
        }, 1000); // Guaranteed render within 1s
    }
    clearTimeout(_renderTimer);
    _renderTimer = setTimeout(() => {
        clearTimeout(_renderMaxTimer);
        _renderMaxTimer = null;
        _renderTimer = null;
        updateStats(allManikins);
        render();
    }, 300); // Debounce: wait 300ms after last event
}

function detectAge(m) {
    if (m.manikin_type) return m.manikin_type; // Trust DB first
    const n = (m.asset_name || '').toLowerCase();
    if (n.includes('ทารก') || n.includes('นีโอ') || n.includes('infant') || n.includes('baby') || n.includes('neonatal')) return 'INFANT';
    if (n.includes('เด็ก') || n.includes('child') || n.includes('paediatric') || n.includes('pediatric') || n.includes('junior')) return 'CHILD';
    if (n.includes('ผู้ใหญ่') || n.includes('adult') || n.includes('anne')) return 'ADULT';
    return null;
}

function ageCss(m) {
    const t = detectAge(m);
    return TYPE_CSS[t] || 'other';
}

function ageEmoji(m) {
    return TYPE_EMOJI[detectAge(m)] || '🤖';
}

/* -------- Fetch -------- */

async function loadJson(filename) {
    const res = await fetch(`${DATA_BASE}/${filename}`);
    if (!res.ok) throw new Error(`Failed to load ${filename}: HTTP ${res.status}`);
    return res.json();
}

async function fetchAll() {
    const [manikins, locations, caps, mcaps] = await Promise.all([
        loadJson('manikins.json'),
        loadJson('locations.json'),
        loadJson('capabilities.json'),
        loadJson('manikin_capabilities.json'),
    ]);

    locationMap = {};
    locations.forEach(l => { locationMap[l.id] = l; });

    capMap = {};
    caps.forEach(c => { capMap[c.id] = c.label_th; });

    manikinCaps = {};
    mcaps.forEach(mc => {
        if (!manikinCaps[mc.sap_id]) manikinCaps[mc.sap_id] = [];
        if (capMap[mc.capability_id]) manikinCaps[mc.sap_id].push(capMap[mc.capability_id]);
    });

    return manikins.map(m => ({ ...m, locationObj: m.location_id ? locationMap[m.location_id] : null }));
}


/* -------- Stats -------- */

function updateStats(all) {
    document.getElementById('stat-total').textContent = all.length;
    document.getElementById('stat-ready').textContent = all.filter(m => m.status === 'ready').length;
    document.getElementById('stat-models').textContent = new Set(all.map(m => m.asset_name)).size;
    document.getElementById('stat-locations').textContent = new Set(all.filter(m => m.location_id).map(m => m.location_id)).size;
}

/* -------- Filter -------- */

function getFiltered() {
    return allManikins.filter(m => {
        const age = detectAge(m);
        if (filterAge !== 'all') {
            const map = { adult: 'ADULT', child: 'CHILD', infant: 'INFANT' };
            if (age !== map[filterAge]) return false;
        }
        if (filterStatus !== 'all' && m.status !== filterStatus) return false;
        if (searchQuery) {
            const q = searchQuery.toLowerCase();
            if (!m.asset_name?.toLowerCase().includes(q) && !m.sap_id?.toLowerCase().includes(q)) return false;
        }
        return true;
    });
}

/* -------- Render: Individual Cards -------- */

function statusBadgeHtml(status) {
    const isKnown = status && STATUS_LABEL.hasOwnProperty(status);
    const cls = isKnown ? STATUS_CLASS[status] : 'other';
    const label = isKnown ? STATUS_LABEL[status] : 'สภาพไม่แน่ชัด';
    return `<span class="status-pill ${cls}">${label}</span>`;
}

function capsHtml(sapId) {
    const caps = manikinCaps[sapId] || [];
    if (!caps.length) return '';
    return `<div class="card-caps">${caps.map(c => `<span class="cap-tag">${esc(c)}</span>`).join('')}</div>`;
}

function renderIndividual(manikins) {
    const grid = document.getElementById('manikin-grid');
    grid.innerHTML = '';
    grid.className = 'showroom-grid';

    manikins.forEach(m => {
        const age = ageCss(m);
        const loc = m.locationObj;
        const locStr = loc ? loc.building : null;

        const card = document.createElement('div');
        card.className = `product-card age-accent-${age}`;
        card.innerHTML = DOMPurify.sanitize(`
        <div class="product-card-top">
          <div class="product-age-badge ${age}">${ageEmoji(m)}</div>
          <div class="product-status">${statusBadgeHtml(m.status)}</div>
        </div>
        <div class="product-body">
          <h3 class="product-name">${m.asset_name ? esc(m.asset_name) : 'ไม่ทราบชื่อ'}</h3>
          ${m.asset_code ? `<div class="product-code">${esc(m.asset_code)}</div>` : ''}
          ${capsHtml(m.sap_id)}
        </div>
        <div class="product-footer">
          ${locStr ? `<div class="product-location"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></svg>${esc(locStr)}</div>` : '<div></div>'}
          <button class="quick-view-btn" data-sap="${esc(m.sap_id)}">รายละเอียด →</button>
        </div>`, { FORCE_BODY: true });
        card.querySelector('.quick-view-btn').addEventListener('click', () => openDrawer(m.sap_id));
        grid.appendChild(card);
    });
}

/* -------- Render: Grouped -------- */

function renderGrouped(manikins) {
    const groups = {};
    manikins.forEach(m => {
        const key = m.asset_name || 'ไม่ทราบชื่อ';
        if (!groups[key]) groups[key] = [];
        groups[key].push(m);
    });

    const grid = document.getElementById('manikin-grid');
    grid.innerHTML = '';
    grid.className = 'grouped-grid';

    Object.entries(groups).sort((a, b) => b[1].length - a[1].length).forEach(([name, units]) => {
        const age = ageCss(units[0]);
        const readyCount = units.filter(u => u.status === 'ready').length;
        const totalCount = units.length;

        const card = document.createElement('div');
        card.className = `group-card age-accent-${age}`;
        card.innerHTML = DOMPurify.sanitize(`
        <div class="group-card-header">
          <div class="group-age-icon ${age}">${ageEmoji(units[0])}</div>
          <div class="group-info">
            <h3 class="group-name">${esc(name)}</h3>
            <div class="group-meta">
              ${TYPE_LABEL[detectAge(units[0])] || 'อื่นๆ'}
              · ${capsHtml(units[0].sap_id) ? manikinCaps[units[0].sap_id]?.slice(0, 2).join(', ') || '' : ''}
            </div>
          </div>
          <div class="group-right">
            <div class="group-count">
              <span class="count-ready">${readyCount}</span>/<span class="count-total">${totalCount}</span>
              <div class="count-label">พร้อมใช้</div>
            </div>
            <svg class="expand-chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="6 9 12 15 18 9"/></svg>
          </div>
        </div>
        <div class="group-card-body">
          <div class="unit-chips"></div>
        </div>`, { FORCE_BODY: true });

        // Build unit chips via DOM API — avoids inline onclick handlers (CSP-friendly)
        const chipsContainer = card.querySelector('.unit-chips');
        units.forEach(u => {
            const cls = STATUS_CLASS[u.status] || 'other';
            const loc = u.locationObj;
            const chip = document.createElement('div');
            chip.className = 'unit-chip';
            chip.innerHTML = DOMPurify.sanitize(`<span class="unit-chip-dot ${cls}"></span>
                              <span class="unit-chip-sap" title="${esc(u.sap_id)}">${esc(maskSap(u.sap_id))}</span>
                              ${loc ? `<span class="unit-chip-loc">${esc(loc.building)}</span>` : ''}`);
            chip.addEventListener('click', () => openDrawer(u.sap_id));
            chipsContainer.appendChild(chip);
        });

        card.querySelector('.group-card-header').addEventListener('click', () => card.classList.toggle('expanded'));
        grid.appendChild(card);
    });
}

/* -------- Quick View Drawer -------- */

function openDrawer(sapId) {
    const m = allManikins.find(x => x.sap_id === sapId);
    if (!m) return;

    const age = ageCss(m);
    const loc = m.locationObj;
    const caps = manikinCaps[sapId] || [];

    document.getElementById('drawer-age-icon').innerHTML = DOMPurify.sanitize(`<span class="drawer-age-badge ${age}">${ageEmoji(m)}</span>`);
    document.getElementById('drawer-name').textContent = m.asset_name || 'ไม่ทราบชื่อ';
    document.getElementById('drawer-sap').textContent = `SAP: ${maskSap(sapId)}`;

    document.getElementById('drawer-body').innerHTML = DOMPurify.sanitize(`
      <div class="drawer-section">
        <div class="drawer-row">
          <span class="drawer-key">สถานะ</span>
          ${statusBadgeHtml(m.status)}
        </div>
        <div class="drawer-row">
          <span class="drawer-key">ช่วงวัย</span>
          <span class="drawer-val">${TYPE_EMOJI[detectAge(m)] || '—'} ${TYPE_LABEL[detectAge(m)] || '—'}</span>
        </div>
        ${m.asset_code ? `<div class="drawer-row"><span class="drawer-key">Asset Code</span><span class="drawer-val">${esc(m.asset_code)}</span></div>` : ''}
        <div class="drawer-row">
          <span class="drawer-key">ที่ตั้ง</span>
          <span class="drawer-val">${loc ? `📍 ${esc(loc.building)}` : '— ไม่ระบุ'}</span>
        </div>
      </div>
      ${caps.length ? `
      <div class="drawer-section">
        <div class="drawer-section-title">ฟังก์ชัน / ความสามารถ</div>
        <div class="drawer-caps">${caps.map(c => `<span class="cap-tag-lg">${esc(c)}</span>`).join('')}</div>
      </div>` : ''}
    `);

    document.getElementById('detail-drawer').classList.add('open');
    document.getElementById('drawer-overlay').classList.add('visible');
    document.body.style.overflow = 'hidden';
}

function closeDrawer() {
    document.getElementById('detail-drawer').classList.remove('open');
    document.getElementById('drawer-overlay').classList.remove('visible');
    document.body.style.overflow = '';
}

/* -------- Master Render -------- */

function render() {
    const filtered = getFiltered();
    document.getElementById('loading').style.display = 'none';

    const empty = document.getElementById('empty-state');
    const grid = document.getElementById('manikin-grid');

    if (filtered.length === 0) {
        grid.innerHTML = '';
        empty.style.display = 'flex';
        document.getElementById('result-count').textContent = 'ไม่พบรายการที่ตรงกัน';
        return;
    }
    empty.style.display = 'none';
    document.getElementById('result-count').textContent = `แสดง ${filtered.length} รายการ`;

    if (viewMode === 'grouped') renderGrouped(filtered);
    else renderIndividual(filtered);
}

/* -------- Event Listeners -------- */

document.getElementById('search-input').addEventListener('input', e => {
    searchQuery = e.target.value.trim();
    document.getElementById('clear-search').style.display = searchQuery ? 'flex' : 'none';
    render();
});

document.getElementById('clear-search').addEventListener('click', () => {
    document.getElementById('search-input').value = '';
    searchQuery = '';
    document.getElementById('clear-search').style.display = 'none';
    render();
});

// Hero category buttons
document.querySelectorAll('.cat-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.cat-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        filterAge = btn.dataset.age;

        // Sync filter-bar status chips labels
        document.querySelectorAll('[data-age]').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        document.querySelector('#catalog').scrollIntoView({ behavior: 'smooth' });
        render();
    });
});

// Status chips
document.getElementById('status-chips').addEventListener('click', e => {
    const btn = e.target.closest('[data-status]');
    if (!btn) return;
    document.querySelectorAll('[data-status]').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    filterStatus = btn.dataset.status;
    render();
});

// View toggle
document.getElementById('btn-grouped').addEventListener('click', () => {
    viewMode = 'grouped';
    document.getElementById('btn-grouped').classList.add('active');
    document.getElementById('btn-individual').classList.remove('active');
    render();
});

document.getElementById('btn-individual').addEventListener('click', () => {
    viewMode = 'individual';
    document.getElementById('btn-individual').classList.add('active');
    document.getElementById('btn-grouped').classList.remove('active');
    render();
});

// Drawer close
document.getElementById('drawer-close').addEventListener('click', closeDrawer);
document.getElementById('drawer-overlay').addEventListener('click', closeDrawer);
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeDrawer(); });

// Nav scroll effect
window.addEventListener('scroll', () => {
    document.getElementById('nav').classList.toggle('scrolled', window.scrollY > 60);
});

// Auto-refresh when tab becomes visible again
document.addEventListener('visibilitychange', () => {
    if (!document.hidden) {
        console.log('[App] Tab visible, fetching latest data...');
        reloadData();
    }
});

/* -------- Realtime -------- */
// Supabase anon key is safe here — RLS blocks access to inactive/private data.
const SUPABASE_RT_URL = 'https://ifogcvymwhcfbfjzhwsl.supabase.co';
const SUPABASE_ANON = 'sb_publishable_DZyIDHVZ-kfD1o3baz0qmw_tTyRCJG8';

function subscribeRealtime() {
    const supabase = window.supabase.createClient(SUPABASE_RT_URL, SUPABASE_ANON);

    supabase
        .channel('manikins-live')
        .on(
            'postgres_changes',
            { event: 'UPDATE', schema: 'public', table: 'manikins', filter: 'is_active=eq.true' },
            (payload) => {
                const updated = payload.new;
                if (!updated || !updated.sap_id) return;

                const idx = allManikins.findIndex(m => m.sap_id === updated.sap_id);

                // Option B: If location changed → full reload to re-sync locationMap from latest JSON
                if (idx !== -1 && allManikins[idx].location_id !== updated.location_id) {
                    console.log('[Realtime] location_id changed — full reload to sync maps');
                    reloadData();
                    return;
                }

                // Option A: Only patch status-related fields (no locationMap dependency)
                if (updated.is_active === false || updated.needs_review === true) {
                    if (idx !== -1) allManikins.splice(idx, 1);
                } else if (idx !== -1) {
                    allManikins[idx] = {
                        ...allManikins[idx],
                        status: updated.status,
                        asset_name: updated.asset_name,
                        manikin_type: updated.manikin_type,
                        // location_id and locationObj intentionally NOT patched here —
                        // location changes use full reload above to stay in sync with locationMap
                    };
                }

                // Debounce re-render to batch burst events (prevents jank)
                scheduleRender();

                // Update timestamp immediately on each event
                const now = new Date();
                document.getElementById('last-updated').textContent =
                    `อัปเดต ${now.toLocaleTimeString('th-TH', { hour: '2-digit', minute: '2-digit', second: '2-digit' })} น.`;
            }
        )
        .subscribe((status) => {
            if (status === 'SUBSCRIBED') {
                console.log('[Realtime] Connected — live updates active');
            }
        });
}

/* -------- Init & Data Load -------- */

async function reloadData() {
    try {
        allManikins = await fetchAll();
        updateStats(allManikins);
        render();

        // Show data freshness from meta.json (written by GitHub Actions)
        try {
            const meta = await loadJson('meta.json');
            const ts = new Date(meta.last_updated);
            document.getElementById('last-updated').textContent =
                `ข้อมูล ณ ${ts.toLocaleString('th-TH', { hour: '2-digit', minute: '2-digit' })} น.`;
        } catch {
            document.getElementById('last-updated').textContent = 'ข้อมูล ณ ตอนนี้';
        }
    } catch (err) {
        document.getElementById('loading').style.display = 'block';
        document.getElementById('loading').innerHTML = `<div class="load-error">❌ โหลดข้อมูลไม่สำเร็จ: ${err.message}</div>`;
        console.error('Data load error:', err);
    }
}

async function init() {
    document.getElementById('loading').style.display = 'flex';
    await reloadData();
    // Subscribe to live updates after initial render
    subscribeRealtime();
}

init();

